find_path(MPFR_INCLUDE_DIRS
  NAMES mpfr.h
)

find_library(MPFR_LIBRARIES mpfr)

add_library(MPFR::gmp UNKNOWN IMPORTED)
set_target_properties(MPFR::gmp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${MPFR_INCLUDE_DIRS}
  IMPORTED_LOCATION ${MPFR_LIBRARIES}

)

find_package_handle_standard_args(MPFR DEFAULT_MSG
  MPFR_INCLUDE_DIRS MPFR_LIBRARIES
)
